In [94]:
import numpy as np
import pandas as pd
from numpy.linalg import inv

df = pd.read_csv('d:\LDA_DATA.csv')
X = np.array(df.a)
Y = np.array(df.b)
Label = np.array(df.c)

X1 = []
Y1 = []
Label1 = []

X2 = []
Y2 = []
Label2 = []

for i in range(len(X)):
    if Label[i] == 0:
        X1.append(X[i])
        Y1.append(Y[i])
        Label1.append(Label[i])
    else:
        X2.append(X[i])
        Y2.append(Y[i])
        Label2.append(Label[i])


meanX1 = np.mean(X1) 
meanY1 = np.mean(Y1)
meanX2 = np.mean(X2) 
meanY2 = np.mean(Y2)

X1 = np.array((X1, Y1))
X2 = np.array((X2, Y2))

mean1 = np.array((meanX1, meanY1))
mean2 = np.array((meanX2, meanY2))
cov1 = np.cov(X1)
cov2 = np.cov(X2)
Sw = cov1 + cov2
omega = np.dot(inv(Sw),(mean1 - mean2))
print(omega)
print(mean1,mean2)
        


[-0.56812958 -0.48149318]
[-0.01865046 -0.05251722] [ 0.94938894  0.89741804]


In [74]:
Z1 = np.dot(omega, X1)
Z2 = np.dot(omega, X2)
meanZ1 = np.dot(omega, mean1)
covZ1 = np.dot(np.dot(omega.T,cov1),omega)
meanZ2 = np.dot(omega, mean2)
covZ2 = np.dot(np.dot(omega.T,cov2),omega)

In [93]:
test= np.array([[2,2],[-1,-1],[0.7,0.7],[0.1,0.1]])
for i in range(4):
    temp = np.dot(omega, test[i])
    if abs(temp-meanZ1) < abs(temp-meanZ2):
        print(0)
    else:
        print(1)

1
0
1
0


In [89]:
meanZ2

-0.97147660275798797

In [91]:
Z1

array([ -2.78230225e-01,   5.41508802e-01,  -7.46289192e-01,
        -1.01864283e+00,  -1.06332604e-01,  -2.37452234e-01,
         4.08191376e-02,   3.19302269e-01,   2.53666355e-01,
         1.32506026e-01,  -1.50856752e+00,   1.16014272e+00,
         1.16868177e+00,   3.49161306e-02,  -8.15369427e-01,
        -5.20355550e-01,  -3.02759704e-01,   5.43696688e-01,
         3.68475421e-01,  -8.35891361e-01,  -2.26222629e-02,
        -1.49619663e+00,  -1.88441102e-02,   9.12908316e-01,
         9.82367589e-01,  -5.61073859e-01,   3.41261282e-01,
         1.67103934e+00,  -9.02730002e-01,  -6.43106518e-01,
        -7.42463595e-01,   1.38008680e+00,  -2.11439170e-01,
         5.23158610e-01,  -6.34370342e-01,   1.93659136e-01,
         6.63079263e-01,  -1.09839403e+00,  -4.69805502e-01,
         5.60474947e-01,  -6.23026606e-01,  -4.38208571e-03,
        -8.72515357e-01,  -3.35111722e-01,   2.61028946e-01,
         8.71263527e-03,  -2.37899528e-01,   5.01884332e-01,
        -7.71703353e-02,

In [51]:
a

array([2, 2])

In [42]:
mean1 - mean2

array([-0.96803939, -0.94993526])

In [37]:
mean1

array([-0.01865046, -0.05251722])

In [38]:
mean2

array(0.9493889366876027)

In [35]:
mean2

array(0.9493889366876027)

In [30]:
len(Sw)

100

In [27]:
type(Sw)

numpy.ndarray

In [28]:
type(mean1)

tuple

In [21]:
len(cov1)

100

In [17]:
cov1

array([[ 0.81681741, -0.12861962],
       [-0.12861962,  1.14240872]])

In [12]:
meanX1

-0.018650455732600362

In [13]:
meanY1

-0.05251722046544683

In [14]:
meanX2

0.94938893668760271

In [3]:
df

Unnamed: 0         a         b    c
0             0  0.710755  0.703592  1.0
1             1  0.741145  0.608881  1.0
2             2  0.448397  2.507375  1.0
3             3  1.646613 -0.203023  1.0
4             4  0.769372  0.292938  1.0
5             5  1.342800  1.674659  1.0
6             6  1.817795  0.984596  1.0
7             7  1.135224  1.223046  1.0
8             8  1.310239  2.695424  1.0
9             9  0.559606  0.153649  1.0
10           10  1.639750  1.155792  1.0
11           11  0.149692 -0.133664  1.0
12           12  2.918324  1.449339  1.0
13           13 -0.313521  1.136270  1.0
14           14  1.925272  0.200536  1.0
15           15  0.854025  1.097048  1.0
16           16  2.216243  0.306707  1.0
17           17  0.685965  0.522559  1.0
18           18 -0.761272  2.748840  1.0
19           19  1.290842  1.215328  1.0
20           20  2.252073  0.782203  1.0
21           21  0.429275  2.294307  1.0
22           22  0.565632 -0.189620  1.0
23           23 -1.021439  1.378304  1.0
24           24  2.029887  0.216930  1.0
25           25  0.776063  0.843511  1.0
26           26  0.120966  1.520581  1.0
27           27  3.278811  1.430012  1.0
28           28  2.297954  0.057475  1.0
29           29  0.982962  1.521607  1.0
..          ...       ...       ...  ...
170         170 -0.239032 -1.146550  0.0
171         171 -1.407072 -0.707907  0.0
172         172  0.315589  0.501155  0.0
173         173 -0.729675  0.571042  0.0
174         174  0.321347 -0.537428  0.0
175         175  0.855223 -0.272362  0.0
176         176 -0.980416 -1.225030  0.0
177         177  1.027338 -1.795216  0.0
178         178 -1.067159 -0.791335  0.0
179         179  0.330572  0.521467  0.0
180         180  0.607037 -1.154011  0.0
181         181 -0.023610 -1.023411  0.0
182         182 -0.116055 -0.773757  0.0
183         183  0.544498 -1.190096  0.0
184         184  1.089538 -0.478444  0.0
185         185 -1.601040 -1.231350  0.0
186         186  0.342282  0.421315  0.0
187         187  0.551537 -0.684527  0.0
188         188 -0.151881 -0.798560  0.0
189         189 -1.081884 -1.011754  0.0
190         190 -0.368171  0.401203  0.0
191         191 -1.481567  0.931934  0.0
192         192 -0.833915 -1.914171  0.0
193         193 -0.105558  0.962591  0.0
194         194  0.959689  0.075147  0.0
195         195  1.189340 -0.699341  0.0
196         196  1.344662 -0.694533  0.0
197         197  0.670322  3.131340  0.0
198         198 -1.195157  1.028332  0.0
199         199  0.549311 -0.775916  0.0

[200 rows x 4 columns]